name: nebria
channels:
    - conda-forge
    - bioconda
dependencies:
    - msprime
    - pyslim
    - tskit
    - numpy
    - scipy
    - jupyterlab
    - matplotlib
    - slim
    - pandas
    - snakemake
    - r-irkernel
    - ipywidgets
    - nodejs
    - widgetsnbextension
    - r-sf
    - r-raster
    - r-stars
    - r-sp
    - r-rgdal
    - r-png
    - r-tidyverse
    - r-tigris
